INSTALL_DIR=~/.config/mircmd/plugins/mircmd/chemistry-object-icons

.PHONY: install
install:
	rm -rf $(INSTALL_DIR)
	mkdir -p $(INSTALL_DIR)
	cp manifest.yaml $(INSTALL_DIR)/
	cp plugin.js $(INSTALL_DIR)/
	cp -r icons $(INSTALL_DIR)/
